### ISSUE TITLE
KMeans Function Enters Infinite Loop in width_expansion.py with center_shift=nan

### ISSUE THREAD

**Issue by 921112343** [Ziyang412/VideoTree#1]
Thank you for open-sourcing this excellent work. I am currently reproducing your project and encountered an issue while running the width_expansion.py script. The KMeans function enters an infinite loop, and the output shows center_shift=nan. However, using the KMeans function from the sklearn.cluster library does not produce this error, though the clustering results differ.

Here is the feature pt file that got error: 
https://drive.google.com/file/d/1z1yaiLcPUSI8Uh2DvcrFpVQ6cBWZSDFg/view?usp=drive_link

Could you please let me know if you have encountered a similar issue before and provide any guidance on how to resolve this?

Thank you for your assistance.

**Comment by Ziyang412** [comment]
Hi, thanks for your attention towards our work. The issue is due to the no iteration limit of the original kmeans_pytorch package. Please follow our updated ReadMe and update the init file within that package and reinstall that. Thanks!
