### ISSUE TITLE
Version of Mistral

### ISSUE THREAD

**Issue by Shiyhm** [Ziyang412/VideoTree#10]
Hi, I noticed that you conducted experiments on Mistral 7B and 12B. However, I found two models on Hugging Face under Mistralai(https://huggingface.co/mistralai): mistral-7B and mistral-7B-instruct. Could you clarify which model was used in your paper? Thanks!

**Comment by Ziyang412** [comment]
Hi, thanks for the question. We follow the setup in [Langrepo](https://github.com/kkahatapitiya/LangRepo), they use "Download [Mistral-7B-Instruct-v0.2](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2) and [Mixtral-8x7B-Instruct-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1) model checkpoints, following the instructions on huggingface." Also our evaluation pipeline followed their log-likelihood evaluation (mentioned in the paper).
