### ISSUE TITLE
Issue with Missing "Frame Relevance" Content in LLM Response

### ISSUE THREAD

**Issue by SiyuJi5** [Ziyang412/VideoTree#2]
Thank you for open-sourcing this excellent work. I am currently reproducing your project and encountered an issue with a specific part of the code.

The function update_relevance_response is supposed to extract relevance information from the response text using the following code:

def update_relevance_response(text):
    response = text
    relevance_match = re.search(r"frame relevance: \[([0-9, ]+)\]", response)
    if relevance_match:
        relevance = list(map(int, relevance_match.group(1).split(',')))
    return relevance
However, my response does not contain any "frame relevance" content, which is expected to be provided by the LLM. The specific response I received is:
'prediction: C, center_shift=0.000000, iteration=6, tol=0.000100] explanation: The actions described involve cleaning kitchen items such as'

Without this information, the function does not work as intended and will meet this error(UnboundLocalError: local variable 'relevance' referenced before assignment).

Have you encountered a similar issue before, where the LLM response lacks the "frame relevance" content? If so, could you provide any guidance or suggestions on how to ensure that the LLM includes this information in its response?

**Comment by Ziyang412** [comment]
I think it is the OpenAI model problem that doesn't output correctly. I think the easiest solution is skip this sample when this sorts of issue encounter. 

In the future (if time allows), I might update the code to tackle this edge cases due to the unstableness of GPT models. Thanks.
