### ISSUE TITLE
May I ask when you plan to release the scripts on the nextqa dataset?

### ISSUE THREAD

**Issue by ontheway-arch** [Ziyang412/VideoTree#5]
In order to better reproduce the results in the paper,  when do you plan to release the nextqa script?

**Comment by Ziyang412** [comment]
Hi, we plan to add the code for next-qa in the next version of the paper/code.  Hopefully we would have the time to do it soon. The caption we get is from the VideoAgent (https://github.com/wxh1996/VideoAgent) paper and the script is similar to EgoSchema, please refer to LLoVi (https://github.com/CeeZh/LLoVi)'s code for more details.
