### ISSUE TITLE
gpt model error

### ISSUE THREAD

**Issue by zhaishengfu** [Ziyang412/VideoTree#6]
![image](https://github.com/user-attachments/assets/ceccd509-febb-4882-a557-093ba459b6ba)
when i run the code `sh scripts/breath_expansion.sh`, there is error as above image shows. and i see the code, the GPT init does not have api_key

![image](https://github.com/user-attachments/assets/f2355521-2091-42da-bf40-b289570fe795)

**Comment by Ziyang412** [comment]
Since we use the Azure APIs, so the code could be slightly different with direct OpenAI APIs. you could reference this code: https://github.com/CeeZh/LLoVi/blob/fd6e34103709efc4f50b188b1102a34e08136da2/model.py#L28. Only slightly changes are needed to run it on.
