### ISSUE TITLE
test for custom video

### ISSUE THREAD

**Issue by zhaishengfu** [Ziyang412/VideoTree#7]
Great work. I have run all the code, and I want to test my custom video. The problem is the frame caption. For example, for Egoschema dataset, we have each frame caption using Lavila. But How to generate this frame caption for my custom video?
 I test the Lavila code, and it input 4 frames and output 10 different sententeces. I do not understand their meaning and how to extend to my custom video caption task.

**Comment by Ziyang412** [comment]
Hi, we use the LaViLA caption from LLoVi repo(https://github.com/CeeZh/LLoVi). In that work, we retrained the LaViLA model and released the checkpoint. Feel free to check it out. 

I am not so sure but just a guess is that: 

_"it input 4 frames and output 10 different sententeces"_

LaViLA model takes in a video clip with four frames, the 10 output captions are different samples of the LLM. Please verify this point.
