### ISSUE TITLE
where is subset_answers.json ,used in extract_features.py

### ISSUE THREAD

**Issue by OutBreak-hui** [Ziyang412/VideoTree#8]
after unzip data.zip, I can not find subset_answers.json

**Comment by Ziyang412** [comment]
Thanks for pointing it out! Please refer to the EgoSchema Official repo for that file. https://github.com/egoschema/EgoSchema.git

**Comment by xmanzhu** [comment]
Hello, the subset_answers.json provided in https://github.com/egoschema/EgoSchema.git only contains 500 videos, so extract_features.py will only process frames from these 500 videos. What about the others?
