### ISSUE TITLE
where is the few_shot_6.json path?

### ISSUE THREAD

**Issue by fake-warrior8** [Ziyang412/VideoTree#9]
Hi, I did not find the few_shot_6.json for running sh scripts/egoschema_qa.sh. Where is it? Moreover, the paper claims to use a zero-shot VideoQA setting, why use few-shot examples?

**Comment by Ziyang412** [comment]
Hi, thanks for the interest. We simply follow the settings of the LLoVi paper ( [https://github.com/CeeZh/LLoVi](url) ). The json is from their repository (https://drive.google.com/file/d/13M10CB5ePPVlycn754_ff3CwnpPtDfJA/view)

**Comment by Ziyang412** [comment]
Also for the "zero-shot claim", we more consider our approach as a training-free method on EgoSchema. On Next-QA/IntentQA/..., where no in-context example is added, we actually conduct zero-shot evaluation. Please refer to our updated version of arxiv to see more details (https://arxiv.org/pdf/2405.19209).

**Comment by fake-warrior8** [comment]
> Also for the "zero-shot claim", we more consider our approach as a training-free method on EgoSchema. On Next-QA/IntentQA/..., where no in-context example is added, we actually conduct zero-shot evaluation. Please refer to our updated version of arxiv to see more details (https://arxiv.org/pdf/2405.19209).

Thank you for your reply.
